### ISSUE TITLE
Import of submodules doesn't work

### ISSUE THREAD

**Issue by peter-conalgo** [switck/libngu#8]
I've managed to compile NgU and it works, but I can't import sub modules in one step.
```python
>>> import ngu
>>> ngu.hash
<module 'hash'>
>>> ngu.hash.ripemd160
<class 'ripemd160'>
>>> from ngu.hash import ripemd160
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'ngu'
>>> from ngu import hash
>>> hash.ripemd160
<class 'ripemd160'>
```

In particular, I'd like to be able to do:
```
>>> import ngu
>>> from ngu.hash import ripemd160 as xx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'ngu'
```

**Comment by switck** [comment]
bug. instead:

```python
import ngu
#from ngu.hdnode import HDNode
HDNode = ngu.hdnode.HDNode
```

**Comment by peter-conalgo** [comment]
Interesting, does that mean you are working on a BIP32 node object too?

I'll see if I can fix this import issues and give a PR.

**Comment by peter-conalgo** [comment]
Sorry, couldn't figure this out... I'll just use the syntax you give above.
